name: BSDs

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  BSDs:
    # Run BSDs using macOS nested virtualization:
    # https://github.com/cross-platform-actions/action#under-the-hood
    runs-on: macOS-latest

    strategy:
      fail-fast: false
      matrix:
        os:
          - name: freebsd
            version: '13.0'
            pkginstall: pkg install -y p5-ExtUtils-MakeMaker
          #- name: freebsd
          #  version: '12.2'
          #  pkginstall: pkg install -y p5-ExtUtils-MakeMaker

          # Tests currently fail on OpenBSD:
          #- name: openbsd
          #  version: '6.9'
          #  pkginstall: pkg_add curl p5-ExtUtils-MakeMaker

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Test on ${{ matrix.os.name }}
        uses: cross-platform-actions/action@a4a7327f8112bc2513a07701786a0c3c1193583a  # v0.23.0
        with:
          operating_system: ${{ matrix.os.name }}
          version: ${{ matrix.os.version }}
          shell: bash
          run: |
            sudo ${{ matrix.os.pkginstall }}
            curl -L https://cpanmin.us | sudo perl - --notest --installdeps --with-configure --with-develop .
            perl Makefile.PL
            make
            prove -wlvmb t
