name: Windows_Installation

on:
  # Manual runs only.  This test uses the CPAN version of IPC::Run, not Perl
  # code at the current commit.  This test would fail even for a commit that,
  # once released, would lead to this test passing.
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.32'
          distribution: strawberry
      - run: perl -V
      - name: Uninstall and Install Module
        run: curl https://cpanmin.us | perl - --verbose --reinstall IPC::Run
